name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    container: adoptopenjdk:11-jdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Store tag name as version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        run: ./gradlew publish -Pversion=${{ env.RELEASE_VERSION }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
